"""Create column taskTitle

Revision ID: 23b0816d287a
Revises: 044ba40e2e89
Create Date: 2025-05-18 14:16:35.389209

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "23b0816d287a"
down_revision: Union[str, None] = "044ba40e2e89"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column("tasks", sa.Column("taskTitle", sa.String(length=30), nullable=False))
    # op.drop_column("tasks", "AllowedRoleIds")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "AllowedRoleIds",
            mysql.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("tasks", "taskTitle")
    # ### end Alembic commands ###
