"""Drop spec

Revision ID: 885ef5ac44a1
Revises: d6504ca2d33d
Create Date: 2025-05-12 17:28:17.282450

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "885ef5ac44a1"
down_revision: Union[str, None] = "d6504ca2d33d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint("tasks_ibfk_2", "tasks", type_="foreignkey")
    # op.drop_column("tasks", "spec_id")
    op.drop_table("specs")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column("spec_id", mysql.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key("tasks_ibfk_2", "tasks", "specs", ["spec_id"], ["id"])
    op.create_table(
        "specs",
        sa.Column("specTitle", mysql.VARCHAR(length=30), nullable=False),
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
