"""-

Revision ID: 6b5a4bec1126
Revises: da7a976c3263
Create Date: 2025-05-02 19:03:25.629777

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6b5a4bec1126"
down_revision: Union[str, None] = "da7a976c3263"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("userLogin", sa.Integer()))
    op.create_unique_constraint(None, "users", ["userLogin"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    # ### end Alembic commands ###
