"""Create columns

Revision ID: b7ef2c903574
Revises: 89519a575e11
Create Date: 2025-05-12 16:52:30.451445

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "b7ef2c903574"
down_revision: Union[str, None] = "89519a575e11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "users", "specs", ["spec_id"], ["id"])
    # op.drop_column("users", "userSpecialization")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("userSpecialization", mysql.VARCHAR(length=50), nullable=False),
    )
    op.drop_constraint(None, "users", type_="foreignkey")
    # ### end Alembic commands ###
