"""Drop sepc_id

Revision ID: d6504ca2d33d
Revises: b7ef2c903574
Create Date: 2025-05-12 17:16:56.125826

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "d6504ca2d33d"
down_revision: Union[str, None] = "b7ef2c903574"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_ibfk_2", "users", type_="foreignkey")
    op.drop_column("users", "spec_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "spec_id", mysql.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "users_ibfk_2", "users", "specs", ["spec_id"], ["id"]
    )
    # ### end Alembic commands ###
