"""Dop products

Revision ID: a78be3b15df8
Revises: b85495934612
Create Date: 2025-05-17 16:03:55.696117

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "a78be3b15df8"
down_revision: Union[str, None] = "b85495934612"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("products")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("name", mysql.VARCHAR(length=50), nullable=True),
        sa.Column(
            "price", mysql.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
