"""Create foreign key for material

Revision ID: 044ba40e2e89
Revises: 1ed61e470de4
Create Date: 2025-05-17 19:49:20.242126

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "044ba40e2e89"
down_revision: Union[str, None] = "1ed61e470de4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categorys",
        sa.Column("categoryTitle", sa.String(length=30), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "materials", sa.Column("category", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "materials", "categorys", ["category"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "materials", type_="foreignkey")
    op.drop_column("materials", "category")
    op.drop_table("categorys")
    # ### end Alembic commands ###
