"""Create table Specializations

Revision ID: 89519a575e11
Revises: 5a1fc05c187b
Create Date: 2025-05-12 15:48:51.839617

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "89519a575e11"
down_revision: Union[str, None] = "5a1fc05c187b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "specs",
        sa.Column("specTitle", sa.String(length=30), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("users", "userSpecialization")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "userSpecialization", mysql.VARCHAR(length=50), nullable=False
        ),
    )
    op.drop_table("specs")
    # ### end Alembic commands ###
