"""Delete column email from User

Revision ID: da7a976c3263
Revises: 9b3544298d77
Create Date: 2025-04-25 16:50:34.147949

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "da7a976c3263"
down_revision: Union[str, None] = "9b3544298d77"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("email", mysql.VARCHAR(length=40), nullable=False)
    )
    # ### end Alembic commands ###
